@startuml
left to right direction
actor Admin
actor Cliente

rectangle "Sistema de Gestión de Órdenes" as system {
    usecase "Subir Orden de Servicio" as UC1
    usecase "Modificar Estado de Orden de Servicio" as UC2
    usecase "Agregar Comentarios" as UC3
    usecase "Consultar Estado de Orden de Servicio" as UC4
    usecase "Consultar Todas las Órdenes Subidas" as UC5
}

Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC5
Cliente --> UC4

@enduml

